name: Build Timecop
on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [created]
jobs:
  build:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.4'
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      - name: PHP version
        run: |
          php --version
      - name: Set PHP_API
        run: |
          echo "PHP_API=$(php-config --phpapi)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          phpize
          ./configure
          make
          make test REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TESTS="--show-all"

